robot_1:
  darknet_ros:
    ros__parameters:
      subscribers:
        camera_reading:
          topic: /robot_1/image_raw
          queue_size: 1
      actions:
        camera_reading:
          topic: /robot_1/check_for_objects
      publishers:
        object_detector:
          topic: /robot_1/found_object
          queue_size: 1
          latch: false
        bounding_boxes:
          topic: /robot_1/bounding_boxes
          queue_size: 1
          latch: false
        detection_image:
          topic: /robot_1/detection_image
          queue_size: 1
          latch: true
      image_view:
        enable_opencv: false
        wait_key_delay: 3
        enable_console_output: true
